# Generated by Django 2.2.11 on 2020-12-29 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAnimal', models.CharField(max_length=100)),
                ('sexAnimal', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMedecin', models.CharField(max_length=100)),
                ('prenomMedecin', models.CharField(max_length=100)),
                ('contactMedcin', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMedicament', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomParent', models.CharField(max_length=100)),
                ('prenomParent', models.CharField(max_length=100)),
                ('contactP', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRdv', models.DateField()),
                ('heureDebut', models.TimeField(default=None)),
                ('heureFin', models.TimeField(default=None)),
                ('animal_rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.Animal')),
                ('medecin_rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.Medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePres', models.DateField()),
                ('frequence', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(default=None)),
                ('medicament_pres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.Medicament')),
                ('ordonnance_pres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.Ordonnance')),
            ],
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='rdv_ord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.Rendezvous'),
        ),
        migrations.AddField(
            model_name='animal',
            name='parent_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.Parent'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VETO.TypeAnimal'),
        ),
    ]
