# Generated by Django 2.2.11 on 2020-12-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='heureDebut',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='heureFin',
            field=models.DateTimeField(default=None),
        ),
    ]
